# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 12c0c71f3d06f53a1aa545d1eaee7fec892aaaa8d5ffed6ef07fcc036e259d1c9a93a3e866fe366f97c6d10f935bfd34742c556853658b891dd1b1ac3221a96c

test:
  secret_key_base: e5da0d1928a33ce3b8967dd085a092e21fc1bc68caa713618c302a985b8f5d66d7e6770fe6ca699115b2bc70dd1481667bd3ff094b956b716de98aae2cd7172a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
